Feature/typescript rewrite
AndrianovaVeronika/clockwise_clockware_backend pull request #12
Opened 2022-09-29 17:35 UTC by AndrianovaVeronika

Rewrited typescript backend

2022-10-03 11:39 UTC, nik-clockwise requested changes

2022-10-03 11:39 UTC, nik-clockwise commented on package.json
> +  "main": "src/index.ts",
кажется main должен быть .js

2022-10-03 11:39 UTC, nik-clockwise commented on package.json
> +    "@types/nodemailer": "6.4.6",
Все типы принято записывать в devDeps т.к. они не влияю на работу выходного кода

2022-10-03 11:39 UTC, nik-clockwise commented on src/config/db.config.ts
> +        host: process.env.DB_HOST as string,
Туту надо попробовать привести типы к нужным. Оператор as это своего рода костыль. В process.env кажется всё строки. А дальше у нас есть bool и number в конфиге

2022-10-03 11:39 UTC, nik-clockwise commented on src/config/db.config.ts
> +        dialect: 'postgres' as Dialect,
тут думаю можем закрыть глаза на as, хотя можно и провалидировать как-то

2022-10-03 11:39 UTC, nik-clockwise commented on src/config/mail.config.ts
> +import "dotenv";
дщтенв загружается раз во входном скрипте, дальше кажется нет необходимости его дергать

2022-10-03 11:39 UTC, nik-clockwise commented on src/config/mail.config.ts
>      port: 465,
надо бы добавить в .env все настройки для меилера

2022-10-03 11:39 UTC, nik-clockwise commented on src/connections/db.connection.ts
> +dotenv.config();
dotenv

2022-10-03 11:39 UTC, nik-clockwise commented on src/controllers/auth/index.ts
> +            const error: any = {};
в идеале вообще нигде никогда не использовать any. Давай просто типизируем ошибку и проблемы не будет, тем более ошибки у нас по всему приложению имеются

2022-10-03 11:39 UTC, nik-clockwise commented on src/controllers/auth/index.ts
> +            const token = req.headers["x-access-token"];
проверку авторизации было бы хорошо вынести в отдельный мидлвар

2022-10-03 11:39 UTC, nik-clockwise commented on src/controllers/order/index.ts
> +        return res.status(500).send({message: e.message});
Этот момет повторяется очень много раз, его нужно вынести в одно место, например в мидлвар (весь try catch)

2022-10-03 11:39 UTC, nik-clockwise commented on src/index.ts
> +export {};
тут у нас же ничего не експортируется, можем убрать совсем

2022-10-03 11:39 UTC, nik-clockwise commented on src/models/city/index.ts
> +class City extends Model<InferAttributes<City>, InferCreationAttributes<City>>
Мне кажется интерфейсы моделей можно переместить в файлы самих моделей, что б не искать по всему проекту

2022-10-03 11:39 UTC, nik-clockwise commented on src/models/index.ts
> +City.hasMany(Order, {foreignKey: 'cityId'});
Описания связей тоже лучше перенести сразу в модели, что бы всё было в одном месте, в каждой модели свои связи

2022-10-03 11:39 UTC, nik-clockwise commented on src/services/city/index.ts
> +    return await City.findAll({
await здесь не нужен и в других подобных местах тоже (если нет .catch в этой цепочке)

2022-10-03 11:39 UTC, nik-clockwise commented on src/services/order/index.ts
> +const orderMapper = (order: RawOrder, withId?: boolean): OrderOutput => order ? ({
А зачем нам тут проверка не "!order"? Только усложняется логика. Нужно уйти от этого. В других местах где опдоное тоже надо рефакторить

2022-10-03 11:39 UTC, nik-clockwise commented on src/services/order/index.ts
> +    return rawOrders.map(order => orderMapper(order, filters?.returnWithIds));
тут не может быть пустого ордера по логике, максимум пустой массив

2022-10-03 11:39 UTC, nik-clockwise commented on src/services/parseTime/index.ts
> +export const parseTimeStringToInt = (time: string) => parseInt(time.substring(0, 2), 10);
думаю тут можно указать возвращаемые значения

2022-10-03 11:39 UTC, nik-clockwise commented on src/services/price/index.ts
> +export const countPrice = async (cityId: number, clockTypeId: number) => {
return type

2022-10-03 11:39 UTC, nik-clockwise commented on src/services/rating/index.ts
> +export const countMasterNewRating = async (orderRating: number, masterId: number): Promise<any> => {
Promise<any> нужно заменить на фактический тип

2022-10-03 11:39 UTC, nik-clockwise commented on src/services/user/index.ts
> +const userMapper = (user: UserRaw): UserOutput => user ? {
нужно все mapperы отрефакторить по логике описанной выше в комментах

2022-10-03 11:39 UTC, nik-clockwise commented on src/types/express/index.d.ts
> +declare global {
Непонятно что ту тпроисходит. Описание глобального реквеста? Не ок говорить что в каждом реквесте могут быть userId и masterId, это же не так

2022-10-03 11:39 UTC, nik-clockwise commented on src/validators/user.validator.ts
> +        email: req.body.email
а если в body нет email?

2022-10-03 21:06 UTC, AndrianovaVeronika commented on package.json
> +  "main": "src/index.ts",
+

2022-10-03 21:06 UTC, AndrianovaVeronika commented on package.json
> +    "@types/nodemailer": "6.4.6",
+

2022-10-03 21:06 UTC, AndrianovaVeronika commented on src/config/mail.config.ts
> +import "dotenv";
+

2022-10-03 21:07 UTC, AndrianovaVeronika commented on src/config/mail.config.ts
>      port: 465,
+

2022-10-03 21:29 UTC, AndrianovaVeronika commented on src/models/city/index.ts
> +class City extends Model<InferAttributes<City>, InferCreationAttributes<City>>
Интерфейсы прикреплены файлами к моделям по типу ../models/city/city.interface, ../models/city/index.ts - сама модель соответственно. Более - интерфейсы Order например не только для создания модели, но и для сервисов.

2022-10-03 21:32 UTC, AndrianovaVeronika commented on src/models/index.ts
> +City.hasMany(Order, {foreignKey: 'cityId'});
Если я опишу связи между моделями до создания одной из них - выдаст ошибку. Я пробовала, но надо сначала описать все модели, а потом уже связи.

2022-10-03 21:44 UTC, AndrianovaVeronika commented on src/services/order/index.ts
> +const orderMapper = (order: RawOrder, withId?: boolean): OrderOutput => order ? ({
В некоторых местах мне нужно ловить undefined вместо order

2022-10-03 21:45 UTC, AndrianovaVeronika commented on src/services/order/index.ts
> +    return rawOrders.map(order => orderMapper(order, filters?.returnWithIds));
Извини, не поняла проблему

2022-10-03 21:47 UTC, AndrianovaVeronika commented on src/services/parseTime/index.ts
> +export const parseTimeStringToInt = (time: string) => parseInt(time.substring(0, 2), 10);
+

2022-10-03 21:48 UTC, AndrianovaVeronika commented on src/services/price/index.ts
> +export const countPrice = async (cityId: number, clockTypeId: number) => {
+

2022-10-03 21:49 UTC, AndrianovaVeronika commented on src/services/rating/index.ts
> +export const countMasterNewRating = async (orderRating: number, masterId: number): Promise<any> => {
Выдает ошибку "The return type of an async function or method must be the global Promise  type. Did you mean to write 'Promise '?". А там вызывается findAll. Promise необходим

2022-10-03 21:51 UTC, AndrianovaVeronika commented on src/types/express/index.d.ts
> +declare global {
Но они "могут быть". К сожалению без этого я не могу получать userId из мидлверов. Нашла только такое решение

2022-10-03 21:55 UTC, AndrianovaVeronika commented on src/validators/user.validator.ts
> +        email: req.body.email
+

2022-10-06 07:44 UTC, nik-clockwise requested changes

2022-10-06 07:44 UTC, nik-clockwise commented on src/controllers/order/index.ts
> +        const newRating = (await ratingService.countMasterNewRating(req.body.rating, targetOrder.masterId));
лишние скобки остались

2022-10-06 07:44 UTC, nik-clockwise commented on src/index.ts
> +dotenv.config();
кажется когда делаешь import, то это dotenv.config() не нужно. Проверь, если да, то можно это убрать и оставить только импорт

2022-10-07 01:03 UTC, AndrianovaVeronika commented on src/index.ts
> +dotenv.config();
Проверила и попробовала, нужно именно запустить конфиг

2022-10-07 11:43 UTC, merged