Feature/pagination filtration sorting
AndrianovaVeronika/clockwise_clockware_backend pull request #22
Opened 2022-10-26 13:36 UTC by AndrianovaVeronika

Sorting and pagination features

2022-10-27 08:12 UTC, nik-clockwise requested changes

2022-10-27 08:12 UTC, nik-clockwise commented on src/controllers/master/index.ts
>          const orders = await orderService.findAll();
Мы тут снова выбераем все миллионы записей из бд, нужно фильтровать сразу в базе

2022-10-27 08:12 UTC, nik-clockwise commented on src/controllers/master/index.ts
> +        const masters = incomeMasters.data.filter(master => master.cities.includes(city.name));
Все фильтры в базу перенести надо

2022-10-27 08:12 UTC, nik-clockwise commented on src/services/user/index.ts
> +        ...(filters?.limit && {limit: filters.limit}),
просто ...filters должно работать ок.
Page отдельно рядом омжно посчитать и добавить в запрос

2022-10-27 08:12 UTC, nik-clockwise commented on src/services/order/index.ts
> +export const findAll = async (filters?: OrderFilters): Promise<{ total: number; data: OrderOutput[] }> => {
обязательно везде нужно указать дефолтные значения для limit, если в фильтре оно не задано

2022-10-28 02:25 UTC, AndrianovaVeronika commented on src/controllers/master/index.ts
>          const orders = await orderService.findAll();
+

2022-10-28 02:25 UTC, AndrianovaVeronika commented on src/controllers/master/index.ts
> +        const masters = incomeMasters.data.filter(master => master.cities.includes(city.name));
+

2022-10-28 02:28 UTC, AndrianovaVeronika commented on src/services/order/index.ts
> +export const findAll = async (filters?: OrderFilters): Promise<{ total: number; data: OrderOutput[] }> => {
+

2022-10-28 02:28 UTC, AndrianovaVeronika commented on src/services/user/index.ts
> +        ...(filters?.limit && {limit: filters.limit}),
+

2022-10-28 02:37 UTC, AndrianovaVeronika commented on src/services/user/index.ts
> +        ...(filters?.limit && {limit: filters.limit}),
Убрала везде, где было лишнее. Оставила только с дополнительными параметрами

2022-10-28 07:50 UTC, nik-clockwise requested changes

2022-10-28 07:50 UTC, nik-clockwise commented on src/models/order/order.interface.ts
> +    date: any;
string, Date?

2022-10-28 07:50 UTC, nik-clockwise commented on src/services/order/index.ts
> +    const limit = filters?.limit || 100;
100 как-то много, у нас показываются по 10-15? Давай дефолт 10 поставим (так всегда ставят), а кому надо больше, в запросе укажет сколько надо. 

Еще 100 дублируется везде, можем вынести в const и менять в одном месте значение дефолтного лимита и оказывать эффект на всё приложение

2022-10-28 11:48 UTC, merged