Feature/master client registration
AndrianovaVeronika/clockwise_clockware_backend pull request #3
Opened 2022-08-26 13:48 UTC by AndrianovaVeronika

2022-08-28 14:52 UTC, X2Style requested changes

2022-08-28 14:52 UTC, X2Style commented on controllers/user.controller.js
> +        const createdUser = await createUserAccount(req.body);
Мы сразу без валидации передаем пользовательский ввод на запись в БД?

2022-08-29 22:44 UTC, X2Style approved these changes
Валидация в отдельной задаче

2022-08-31 17:12 UTC, nik-clockwise approved these changes

2022-08-31 18:40 UTC, merged