Feature/order state price
AndrianovaVeronika/clockwise_clockware_backend pull request #5
Opened 2022-09-06 23:07 UTC by AndrianovaVeronika

2022-09-07 10:35 UTC, nik-clockwise commented on validators/authJwt.js
> +    isMaster: isMaster
isAdmin isMaster получается не имеют никакого отношения к jwt, давай вынесем это куда-то в другое место. Может в отдельный сервис или в модель User например

2022-09-07 10:35 UTC, nik-clockwise commented on migrations/20220831121623-create-price.js
> -'use strict';
Миграция create-price удалена, а табилцы остались. Нужно оставить эту миграцию и создать новую для удаления  таблицы.

2022-09-07 10:35 UTC, nik-clockwise commented on controllers/auth.controller.js
> +exports.isUserCreated = async (req, res) => {
получается что это еще один способ зарегистрироваться? Название не совсем отображает суть метода, давай как-то переименуем это дело в более понятное название

2022-09-08 10:45 UTC, AndrianovaVeronika commented on validators/authJwt.js
> +    isMaster: isMaster
Перемещены в roles.validator

2022-09-08 10:46 UTC, AndrianovaVeronika commented on migrations/20220831121623-create-price.js
> -'use strict';
Так как это осталось на ветке feature удалила все что связано было с model pice, а миграцию откатила

2022-09-08 10:47 UTC, AndrianovaVeronika commented on controllers/auth.controller.js
> +exports.isUserCreated = async (req, res) => {
переименова на createUserOrFindIfAuthorized

2022-09-08 17:50 UTC, nik-clockwise commented on migrations/20220831121623-create-price.js
> -'use strict';
Нужно оставить эту миграцию и создать новую для удаления таблицы.

2022-09-08 18:03 UTC, nik-clockwise requested changes
Надо вернуть удаленную миграцию для консистености т.к. у нас может быть production который работал по старой схеме уже год и нельзя просто взять и вырезать миграцию т.к. есть риск поломать всё. Нужна спец миграция для отката не нужной миграции обратно. 

Если это просто создание/удаление таблицы, то например можно вызвать ту миграцию толкьо up вызвать down и наоборот, таким образом не придется писать новый sql код, а использовать готовую миграцию

2022-09-09 07:43 UTC, nik-clockwise requested changes
Ну теперь надо новую миграцию в которой мы откатим таблицу Prices вызовом migrations/20220831121623-create-price.js -> down

2022-09-09 11:49 UTC, nik-clockwise approved these changes

2022-09-09 11:49 UTC, merged